easy_admin:
  design:
    menu:
#      - { route: 'home', label: 'Home', default: true, icon: 'home' }
      - { entity: 'User', label: 'My Relevant Entity', icon: 'briefcase' }
  entities:
    User:
      class: App\Entity\User
      form:
        fields:
          - { property: 'username' }
          - { property: 'email' }
          - property: 'roles'
            type: 'choice'
            type_options:
              mapped: true
              expanded: true
              multiple: true
              choices: { 'User': 'ROLE_USER', 'Administrator': 'ROLE_ADMIN' }