version: '3.6'

networks:
  nginx-php81-mysql8-node:

services:
  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - logs:/var/log/nginx
    depends_on:
      - php81-service
      - db
    networks:
      - nginx-php81-mysql8-node

  # php
  php81-service:
    build:
      context: .
      dockerfile: Docker/php/Dockerfile
    container_name: php81
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/project
    networks:
      - nginx-php81-mysql8-node
  db:
    image: "postgres:latest"
    restart: always
    env_file:
      - .env
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/logs:z
    ports:
      - 5432:5432
    networks:
      - nginx-php81-mysql8-node
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"

volumes:
    postgres_data:
    postgres_logs:
    logs: