controllers:
    resource: ../src/Controller/
    type: attribute

default_controller:
    path: /register
    controller: App\Controller\DefaultController::register

app.swagger_ui:
    path: /doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
